#!/usr/bin/env node
// Vendors the country flags this app can actually show into static/flags/, and writes
// the list of what landed there to src/lib/data/flag-assets.generated.ts.
//
// Why vendored rather than fetched: AGENTS.md's no-backend rule means the app is a
// static bundle, and a third-party flag CDN would see every visitor's traffic for
// nothing in return. Why a subset rather than the whole set: the source ships 430 SVGs
// (subdivisions, historical flags, non-country codes) at 301 KiB, and this app can only
// ever name a country that has an airport in airports.generated.json, 234 of them at
// 147 KiB. Half the bytes for none of the coverage.
//
// Source: circle-flags (https://github.com/HatScripts/circle-flags), MIT, whose LICENSE
// file is copied to static/flags/LICENSE.md alongside the SVGs so the licence travels
// with the copies the way MIT requires. Checked before use, because issue #11 already
// rejected a flag/icon set whose README claimed a licence the repository did not carry:
// this one's LICENSE.md is a real file in the published npm package, not a README claim.
//
// Run manually with `pnpm run data:flags` when the airport dataset gains a country or
// the upstream package is updated. The output is committed so `pnpm build` never
// depends on node_modules or a network.

import { createRequire } from 'node:module';
import { mkdir, copyFile, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = fileURLToPath(new URL('..', import.meta.url));
const OUTPUT_DIR = path.join(root, 'static', 'flags');
const CODE_LIST_PATH = path.join(root, 'src', 'lib', 'data', 'flag-assets.generated.ts');
const AIRPORTS_PATH = path.join(root, 'src', 'lib', 'data', 'airports.generated.json');

const packageDir = path.dirname(require.resolve('circle-flags/package.json'));
const packageJson = JSON.parse(await readFile(path.join(packageDir, 'package.json'), 'utf-8'));
const sourceDir = path.join(packageDir, 'flags');

const airports = JSON.parse(await readFile(AIRPORTS_PATH, 'utf-8'));
const wanted = [...new Set(airports.map((a) => a.countryCode).filter(Boolean))]
	.map((code) => code.toLowerCase())
	.sort();

const available = new Set(
	(await readdir(sourceDir)).filter((f) => f.endsWith('.svg')).map((f) => f.slice(0, -4))
);
const missing = wanted.filter((code) => !available.has(code));

await rm(OUTPUT_DIR, { recursive: true, force: true });
await mkdir(OUTPUT_DIR, { recursive: true });

let bytes = 0;
const copied = [];
for (const code of wanted) {
	if (!available.has(code)) continue;
	const from = path.join(sourceDir, `${code}.svg`);
	await copyFile(from, path.join(OUTPUT_DIR, `${code}.svg`));
	bytes += (await readFile(from)).length;
	copied.push(code);
}
await copyFile(path.join(packageDir, 'LICENSE.md'), path.join(OUTPUT_DIR, 'LICENSE.md'));

const header = `// Generated by scripts/prepare-flags.mjs. Do not edit by hand.
//
// Which two-letter codes have a file in static/flags/. \`Flag.svelte\` renders an <img>
// only for a code in this set, which is what makes a broken flag image unrepresentable
// rather than merely unlikely (issue #11's acceptance: "never a broken one"). A country
// this app has no airport in is simply not in here, and the component draws its neutral
// placeholder instead.
//
// Source: circle-flags ${packageJson.version} (MIT). See static/flags/LICENSE.md.
`;
const body = `\nexport const FLAG_ASSET_CODES: ReadonlySet<string> = new Set([\n${copied
	.map((code) => `\t'${code}'`)
	.join(',\n')}\n]);\n`;
await writeFile(CODE_LIST_PATH, header + body, 'utf-8');

console.log(
	`flags: ${copied.length} of ${wanted.length} wanted codes copied (${(bytes / 1024).toFixed(0)} KiB) ` +
		`from circle-flags ${packageJson.version}`
);
if (missing.length > 0) {
	// Not fatal: the component falls back to its placeholder for these, which is the
	// same treatment an airport with no country code gets.
	console.log(`no flag available upstream for: ${missing.join(', ')}`);
}
