// Generated by scripts/fetch-exchange-rates.mjs. Do not edit by hand.
//
// European Central Bank daily reference rates, one euro in each currency, read through
// api.frankfurter.dev. Refreshed by .github/workflows/exchange-rates.yml and consumed by
// src/lib/data/exchange-rates.ts, which is the only module that should import this one.
//
// A .ts module rather than JSON because this is imported statically and therefore reaches
// Playwright's plain-Node config loader, which refuses a JSON import without an import
// attribute. See fetch-exchange-rates.mjs for the measurement.

export interface ExchangeRatesFile {
	/** ISO instant CI read these. Our clock. */
	readonly fetchedAt: string;
	/** The day the ECB says these rates are for. Their clock, and the older of the two. */
	readonly referenceDate: string;
	readonly base: 'EUR';
	readonly rates: Readonly<Record<string, number>>;
}

export const EXCHANGE_RATES: ExchangeRatesFile = {
	fetchedAt: '2026-09-08T19:33:20.394Z',
	referenceDate: '2026-09-08',
	base: 'EUR',
	rates: {
		AUD: 1.6098,
		BRL: 5.936,
		CAD: 1.6033,
		CHF: 0.9425,
		CNY: 7.7936,
		CZK: 24.186,
		DKK: 7.4748,
		EUR: 1,
		GBP: 0.8574,
		HKD: 9.1068,
		HUF: 363.95,
		IDR: 20436.92,
		ILS: 3.4979,
		INR: 110.1315,
		ISK: 140.4,
		JPY: 179.2,
		KRW: 1558.22,
		MXN: 19.6869,
		MYR: 4.717,
		NOK: 10.745,
		NZD: 1.9877,
		PHP: 72.597,
		PLN: 4.3178,
		RON: 5.25,
		SEK: 11.152,
		SGD: 1.4701,
		THB: 38.227,
		TRY: 56.2814,
		USD: 1.1614,
		ZAR: 18.6103
	}
};
