// Generated by scripts/fetch-exchange-rates.mjs. Do not edit by hand.
//
// European Central Bank daily reference rates, one euro in each currency, read through
// api.frankfurter.dev. Refreshed by .github/workflows/exchange-rates.yml and consumed by
// src/lib/data/exchange-rates.ts, which is the only module that should import this one.
//
// A .ts module rather than JSON because this is imported statically and therefore reaches
// Playwright's plain-Node config loader, which refuses a JSON import without an import
// attribute. See fetch-exchange-rates.mjs for the measurement.

export interface ExchangeRatesFile {
	/** ISO instant CI read these. Our clock. */
	readonly fetchedAt: string;
	/** The day the ECB says these rates are for. Their clock, and the older of the two. */
	readonly referenceDate: string;
	readonly base: 'EUR';
	readonly rates: Readonly<Record<string, number>>;
}

export const EXCHANGE_RATES: ExchangeRatesFile = {
	fetchedAt: '2026-09-07T20:07:27.589Z',
	referenceDate: '2026-09-07',
	base: 'EUR',
	rates: {
		AUD: 1.6109,
		BRL: 5.9576,
		CAD: 1.6062,
		CHF: 0.9405,
		CNY: 7.7995,
		CZK: 24.197,
		DKK: 7.4746,
		EUR: 1,
		GBP: 0.85894,
		HKD: 9.1119,
		HUF: 363.2,
		IDR: 20509.29,
		ILS: 3.4991,
		INR: 109.821,
		ISK: 140.8,
		JPY: 179.85,
		KRW: 1566.56,
		MXN: 19.6552,
		MYR: 4.7023,
		NOK: 10.774,
		NZD: 1.978,
		PHP: 72.801,
		PLN: 4.3103,
		RON: 5.2519,
		SEK: 11.162,
		SGD: 1.4716,
		THB: 38.231,
		TRY: 56.289,
		USD: 1.1622,
		ZAR: 18.5856
	}
};
