// Generated by scripts/fetch-exchange-rates.mjs. Do not edit by hand.
//
// European Central Bank daily reference rates, one euro in each currency, read through
// api.frankfurter.dev. Refreshed by .github/workflows/exchange-rates.yml and consumed by
// src/lib/data/exchange-rates.ts, which is the only module that should import this one.
//
// A .ts module rather than JSON because this is imported statically and therefore reaches
// Playwright's plain-Node config loader, which refuses a JSON import without an import
// attribute. See fetch-exchange-rates.mjs for the measurement.

export interface ExchangeRatesFile {
	/** ISO instant CI read these. Our clock. */
	readonly fetchedAt: string;
	/** The day the ECB says these rates are for. Their clock, and the older of the two. */
	readonly referenceDate: string;
	readonly base: 'EUR';
	readonly rates: Readonly<Record<string, number>>;
}

export const EXCHANGE_RATES: ExchangeRatesFile = {
	fetchedAt: '2026-09-05T15:25:11.296Z',
	referenceDate: '2026-09-04',
	base: 'EUR',
	rates: {
		AUD: 1.6134,
		BRL: 5.9405,
		CAD: 1.6038,
		CHF: 0.9405,
		CNY: 7.7994,
		CZK: 24.189,
		DKK: 7.4747,
		EUR: 1,
		GBP: 0.85898,
		HKD: 9.112,
		HUF: 363.28,
		IDR: 20496.04,
		ILS: 3.4954,
		INR: 109.8165,
		ISK: 140.8,
		JPY: 181.59,
		KRW: 1569.38,
		MXN: 19.6401,
		MYR: 4.7005,
		NOK: 10.8035,
		NZD: 1.9755,
		PHP: 72.812,
		PLN: 4.3148,
		RON: 5.253,
		SEK: 11.1005,
		SGD: 1.4724,
		THB: 38.26,
		TRY: 56.2995,
		USD: 1.1622,
		ZAR: 18.5571
	}
};
