// Generated by scripts/prepare-icons.mjs. Do not edit by hand.
//
// The 24 icons this app draws, and no others: Tabler ships 5130 and the rest
// of them are not in this file, so they cannot reach a browser. `Icon.svelte` renders one
// <path> per string here, on Tabler's own 24-unit grid at its own stroke weight, which is
// what makes the whole set one weight instead of fifteen hand-drawn approximations of one.
// One entry is composed rather than copied; its comment says which and from what.
//
// Source: @tabler/icons 3.46.0 (MIT). See tabler-icons.LICENSE beside this file.
// Add a name to ICON_NAMES in the script and run `pnpm run data:icons`; the script refuses
// a name no source file uses, so this list cannot drift ahead of the app.

export const TABLER_ICON_PATHS = {
	/** ErrorState, severity warning */
	'alert-triangle': [
		'M12 9v4',
		'M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0',
		'M12 16h.01'
	],
	/** FlightPicker, departure to arrival */
	'arrow-right': [
		'M5 12l14 0',
		'M13 18l6 -6',
		'M13 6l6 6'
	],
	/** SearchForm, swap origin and destination */
	'arrows-up-down': [
		'M7 3l0 18',
		'M10 6l-3 -3l-3 3',
		'M20 18l-3 3l-3 -3',
		'M17 21l0 -18'
	],
	/** ModeIcon, the stopover night */
	bed: [
		'M5 9a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
		'M22 17v-3h-20',
		'M2 8v9',
		'M12 14h10v-2a3 3 0 0 0 -3 -3h-7v5'
	],
	/** ModeIcon, public transport */
	bus: [
		'M4 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
		'M16 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
		'M4 17h-2v-11a1 1 0 0 1 1 -1h14a5 7 0 0 1 5 7v5h-2m-4 0h-8',
		'M16 5l1.5 7l4.5 0',
		'M2 10l15 0',
		'M7 5l0 5',
		'M12 5l0 5'
	],
	/** ModeIcon, driving */
	car: [
		'M5 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
		'M15 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
		'M5 17h-2v-6l2 -5h9l4 5h1a2 2 0 0 1 2 2v4h-2m-4 0h-6m-6 -6h15m-6 0v-5'
	],
	/** a chosen option: the nights rung, the time format, the currency */
	check: [
		'M5 12l5 5l10 -10'
	],
	/** Select, a menu that opens downwards */
	'chevron-down': [
		'M6 9l6 6l6 -6'
	],
	/** DateWindowPicker, earlier months */
	'chevron-left': [
		'M15 6l-6 6l6 6'
	],
	/** DateWindowPicker, later months */
	'chevron-right': [
		'M9 6l6 6l-6 6'
	],
	/** ProviderKeyCard, a key that worked */
	'circle-check': [
		'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0',
		'M9 12l2 2l4 -4'
	],
	/** ErrorState, severity error */
	'circle-x': [
		'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0',
		'M10 10l4 4m0 -4l-4 4'
	],
	/** ModeIcon, the airport wait */
	clock: [
		'M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0',
		'M12 7v5l3 3'
	],
	/** ModeIcon, a transit transfer that rides the water */
	ferry: [
		'M2 18h15.293c1.02 0 1.972 -.503 2.536 -1.34l2.171 -3.66h-18.479l-1.521 5',
		'M14 8l-1 -2',
		'M6.107 12.675l1.384 -4.675h8l2.675 4.598'
	],
	/** ErrorState, severity info */
	'info-circle': [
		'M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0',
		'M12 9h.01',
		'M11 12h1v4h1'
	],
	/** GroundLegPreviews, open the full map */
	maximize: [
		'M4 8v-2a2 2 0 0 1 2 -2h2',
		'M4 16v2a2 2 0 0 0 2 2h2',
		'M16 4h2a2 2 0 0 1 2 2v2',
		'M16 20h2a2 2 0 0 0 2 -2v-2'
	],
	/** ModeIcon, the flight */
	plane: [
		'M16 10h4a2 2 0 0 1 0 4h-4l-4 7h-3l2 -7h-4l-2 2h-3l2 -4l-2 -4h3l2 2h4l-2 -7h3l4 7'
	],
	/** the app header settings link */
	settings: [
		'M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065',
		'M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0'
	],
	/** the settings privacy banner */
	'shield-check': [
		'M11.46 20.846a12 12 0 0 1 -7.96 -14.846a12 12 0 0 0 8.5 -3a12 12 0 0 0 8.5 3a12 12 0 0 1 -.09 7.06',
		'M15 19l2 2l4 -4'
	],
	/** ModeIcon, a taxi: Tabler has no taxi icon (Tabler 'car' plus M8 5h3) */
	taxi: [
		'M5 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
		'M15 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
		'M5 17h-2v-6l2 -5h9l4 5h1a2 2 0 0 1 2 2v4h-2m-4 0h-6m-6 -6h15m-6 0v-5',
		'M8 5h3'
	],
	/** EmptyState, nothing issued yet */
	ticket: [
		'M15 5l0 2',
		'M15 11l0 2',
		'M15 17l0 2',
		'M5 5h14a2 2 0 0 1 2 2v3a2 2 0 0 0 0 4v3a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-3a2 2 0 0 0 0 -4v-3a2 2 0 0 1 2 -2'
	],
	/** ModeIcon, a transit transfer that rides rails */
	train: [
		'M21 13c0 -3.87 -3.37 -7 -10 -7h-8',
		'M3 15h16a2 2 0 0 0 2 -2',
		'M3 6v5h17.5',
		'M3 11v4',
		'M8 11v-5',
		'M13 11v-4.5',
		'M3 19h18'
	],
	/** ModeIcon, walking */
	walk: [
		'M12 4a1 1 0 1 0 2 0a1 1 0 1 0 -2 0',
		'M7 21l3 -4',
		'M16 21l-2 -4l-3 -3l1 -6',
		'M6 12l2 -3l4 -1l3 3l3 1'
	],
	/** dismiss: a chip, a saved search, the map dialog, a duration rule */
	x: [
		'M18 6l-12 12',
		'M6 6l12 12'
	]
} as const;

/** Every icon a caller may ask `Icon.svelte` for. A name outside this union is a type
 *  error rather than an empty <svg> nobody notices until it is on screen. */
export type IconName = keyof typeof TABLER_ICON_PATHS;
